### ISSUE TITLE
how to use env variable

### ISSUE THREAD

**Issue by abehbatre** [kings1990/fast-request#11]
hi, great plugin btw, 
but i have one question 
how to use env variable? 

![ss](https://i.postimg.cc/MZ1Bjt2q/Screenshot-at-Oct-30-06-41-51.png)

**Comment by kings1990** [comment]
not support so far, Env is short for environment like local、dev、prod.

please see the document [https://kings1990.github.io/restful-fast-request-doc/en/guide/getstarted/#project-env-domain](https://kings1990.github.io/restful-fast-request-doc/en/guide/getstarted/#project-env-domain)

As of now, I'm adding the ability to quickly switch header variables into next version 2.0.7
