### ISSUE TITLE
Url Params数组和集合类型参数名不正确

### ISSUE THREAD

**Issue by shoaky009** [kings1990/fast-request#13]
### 当前使用版本(Current Version)
2.0.6

### 重现步骤(Repeat steps)
- 最好提供gif动图(It's best to provide a GIF)
`    @GetMapping("/test")
    void test(@RequestParam("ids") List<Long> ids) {
}
`

上面的代码会生成ids[]的参数名 导致SpringMVC抛出MissingServletRequestParameterException

看了一下源码RequestParamParse这里都是给参数名加上了方括号感觉可以不用加

**Comment by kings1990** [comment]
public String testSetParam(@RequestParam(value="address[]") Set<String> address) throws Exception {}

传参Key:address[]  value: 1,2,3

**Comment by shoaky009** [comment]
了解 但是我认为插件生成参数名最好以RequestParam里面的优先 然后才是方法的参数名

**Comment by kings1990** [comment]
现在就是优先取得@RequestParam和PathVariable中的value，如果没有则取参数的参数名

问题在针对list和数组做了特殊处理加了个[],感谢指正，下个版本2.0.7修复

**Comment by kings1990** [comment]
update to 2.0.7
