### ISSUE TITLE
如何在请求时自动携带认证信息？

### ISSUE THREAD

**Issue by NotEdibleSalt** [kings1990/fast-request#19]
在请求接口时，如何能自动携带认证信息，如token

**Comment by kings1990** [comment]
headers里面添加即可

**Comment by NotEdibleSalt** [comment]
我的意思时能不能在一个地方设置，之后在在请求其他接口的时候都能携带这个token？就是能不能设置全局的header？

**Comment by kings1990** [comment]
headers目前就是全局的且单独的，不随接口的变化而变化，而且支持根据不同env和project自动切换

**Comment by NotEdibleSalt** [comment]
嗯嗯，好的
