### ISSUE TITLE
Set类型无法生成参数

### ISSUE THREAD

**Issue by shoaky009** [kings1990/fast-request#5]
### 当前使用版本(Current Version)
2.0.2
### 重现步骤(Repeat steps)
<a href="https://imgur.com/33kgZPl"><img src="https://i.imgur.com/33kgZPl.gif" title="source: imgur.com" /></a>

### 修复建议
判断是否Collection类型来生成参数

**Comment by kings1990** [comment]
fix in 2.0.3
